### ISSUE TITLE
Mobile meta tag

### ISSUE THREAD

**Issue by Mikeysax** [Muzzh/Splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by Muzzh** [comment]
I was actually thinking that last night, how it didn't look too good on my phone!
I just updated with the tag in the header as well as the CSS for E10

Thanks for the comment !

**Comment by Mikeysax** [comment]
:+1:
